### ISSUE TITLE
Create a reusable workflow that generates a list of Pantheon sites from a list of tags

### ISSUE THREAD

**Issue by slaymoore** [uaz-web/reusable-workflows#1]
A common pattern for using Kraken jobs is to generate a list of Pantheon site names from Pantheon tags. It would be useful to have a single workflow that generates a sites.txt file that contains a list of Pantheon sites from a comma separated list of Pantheon tags; then, any of our Kraken jobs could call this single workflow to get a list of sites to run the job on.

**Comment by slaymoore** [comment]
This could be part of a larger step that sets up PHP, Terminus, and SSH key.

**Comment by KyleClements13** [comment]
Update: Started working on workflow but put on hold for other tools.
